### ISSUE TITLE
Rename Start to Init or add NewRouter() method

### ISSUE THREAD

**Issue by felixge** [ant0ine/go-urlrouter#2]
Hi,

I just saw your post on HN, and found your project very interesting. When looking through the README I noticed that you have Start() method that initializes the data structure, which confused me right away. My reaction was: "Wait, is he starting a server from the router here?". Turns out you're not, and your lib is super sane. However, I'd think renaming this method to `Init()` or providing a `NewRouter()` function that returns an initialized data structure would be much more idiomatic here!

HTH,
Felix

**Comment by felixge** [comment]
I guess I submitted a duplicate of #1, so I'm closing this. Consider me a +1 on adding a constructor : )

**Comment by ant0ine** [comment]
Thanks for the comment! Yes, there is already a pull request open. The thing is that I may want to merge go-urlrouter into go-json-rest. In that case I probably won't need the constructor.
